api_platform:
    title: Marvin
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        extra_properties:
            rfc_7807_compliant_errors: true
            standard_put: true
            event_listeners_backward_compatibility_layer: false
    use_symfony_listeners: true
    show_webby: false
