mqtt:
  server: '!secret.yaml server'
  base_topic: zigbee2mqtt
  user: '!secret.yaml user'
  password: '!secret.yaml password'
  client_id: zigbee_mqtt_marvin
  version: 5
advanced:
  network_key:
    - 94
    - 62
    - 103
    - 203
    - 180
    - 52
    - 12
    - 169
    - 175
    - 190
    - 29
    - 202
    - 16
    - 44
    - 49
    - 202
serial:
  port: /dev/ttyACM0
  adapter: zstack
  disable_led: true
frontend:
  enabled: false
device_options: {}
version: 4
